name: Deploy Frontend to Testing Server

on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USER }}
          key: ${{ secrets.TEST_SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/shippers-frontend
            git pull origin testing

            # Stop and remove old container
            docker stop shippers_frontend || true
            docker rm shippers_frontend || true

            # Rebuild and run the new image
            docker build -t shippers-frontend:latest .
            docker run -d --name shippers_frontend -p 3000:80 shippers-frontend:latest
